
backend:
  name: git-gateway
  branch: main
local_backend: true
publish_mode: editorial_workflow
site_url: "https://accessibility-in-action.inclusivedesign.ca"
media_folder: "src/assets/media"
public_folder: "/assets/media"
collections:
  - name: updates
    label: Updates
    label_singular: Update
    folder: "src/updates"
    slug: "{{slug}}"
    preview_path: "/updates/{{slug}}"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", timeFormat: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: pages
    label: Pages
    label_singular: Page
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "/{{slug}}/"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: blueprint-steps
    label: Blueprint Steps
    label_singular: Blueprint Step
    folder: "src/blueprint-steps"
    slug: "{{slug}}"
    preview_path: "/resources/service-blueprint/{{slug}}/"
    sortable_fields: [title, step]
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Step Number", name: "step", widget: "number", min: 1, value_type: "float", step: 1}
      - label: "For"
        name: "for"
        widget: "select"
        options:
        - { label: "Consultants", value: "consultants" }
        - { label: "Entities", value: "entities" }
        - { label: "Both", value: "both" }
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - {label: "Content", name: "content", widget: "markdown", buttons: [bold, italic, link, bulleted-list, numbered-list], editor_components: []}
  - name: steps
    label: Map Steps
    label_singular: Map Step
    folder: "src/steps"
    slug: "{{slug}}"
    preview_path: "/process-map/{{slug}}/"
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text"}
      - {label: "Phase", name: "phase", widget: "select", options: ["Recruitment", "Preparing consultants", "Preparing federally regulated entities", "Preparing together", "Consultation", "After consultation"]}
      - {label: "Step Number", name: "step", widget: "number", min: 1, value_type: "float", step: 0.1}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: sessions
    label: Sessions
    label_singular: Session
    folder: "src/sessions"
    slug: "{{slug}}"
    preview_path: "/sessions/{{slug}}/"
    sortable_fields: [title, start]
    editor:
      preview: false
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start", name: "start", widget: "datetime"}
      - {label: "End", name: "end", widget: "datetime"}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Preview Image", name: "metaImage", widget: "image", required: false}
      - {label: "Preview Image Alt Text", name: "metaImageAlt", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
