name: Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
